import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { YearGroupStats, YearGroupAttendance, SexStats, AttendanceStats, Student } from '../models/dashboard.interface';

@Injectable({
    providedIn: 'root'
})
export class SchoolDataMockService {
    getStudentsYearGroup(): Observable<YearGroupStats> {
        return of({
            test: { Male: 1 },
            'Groep 7': { Female: 4 },
            'Year 7': { Female: 24, Male: 29 },
            'Groep 8': { Male: 2 },
            'Year 8': { Female: 22, Male: 19 },
            'Peuters 1': { Female: 1 },
            'Groep 5': { Male: 1, Female: 2 },
            Reception: { Female: 15, Male: 24 },
            'Year 9': { Male: 27, Female: 25 },
            'Year 13': { Male: 23, Female: 21 },
            'Groep 6': { Female: 1, Male: 1 },
            'Year 12': { Male: 21, Female: 29 },
            'Year 3': { Female: 28, Male: 26 },
            'Year 11': { Female: 17, Male: 35 },
            'Groep 4': { Male: 1, Female: 1 },
            Nursery: { Female: 7, Male: 13 },
            'Year 4': { Male: 26, Female: 42 },
            'Year 10': { Female: 17, Male: 25 },
            'Groep 1': { Male: 2 },
            'Year 5': { Female: 36, Male: 28 },
            'Year 6': { Female: 21, Male: 28 },
            'Year 1': { Female: 16, Male: 23 },
            'Year 2': { Male: 33, Female: 37 }
        });
    }

    getStudentsAttendanceYearGroup(): Observable<YearGroupAttendance> {
        return of({
            '011': 32,
            '022': 200,
            '016': 289,
            '017': 205,
            '018': 327,
            '019': 187,
            '020': 309,
            '021': 205
        });
    }

    getSexStats(): Observable<SexStats> {
        return of({
            Male: 388,
            Female: 366
        });
    }

    getAttendance(): Observable<AttendanceStats> {
        return of({
            ABSENT: 19,
            PARTIAL: 49,
            FULL: 298
        });
    }

    getStudentsByYearGroupCode(yearGroupCode?: string): Observable<Student[]> {
        return of([
            {
                schoolId: 'CL1-NCBIS',
                status: 'Current',
                pupilId: '868',
                admissionNumber: 746,
                pupilCode: 'TADR03',
                familyNumber: '',
                surname: 'Tadros',
                forename: 'Sarah',
                middlename: '',
                displayName: 'Sarah Tadros',
                preferredForename: 'Sarah',
                preferredSurname: 'Tadros',
                genderCode: 'F',
                gender: 'Female',
                dob: '2008-08-18T00:00:00.000+00:00',
                formName: ' ',
                yearGroupCode: '022',
                yearGroup: 'Year 13',
                registrationGroupCode: '0000',
                registrationGroup: ' ',
                registrationGroupText: '',
                houseCode: '0001',
                house: 'Fire',
                ncYearGroupCode: '00',
                ncYearGroup: ' ',
                address: 'Villa 11 Katameyia Heights  New Cairo  002',
                postCode: '',
                upn: '',
                studentEmailAddress: 'sarah.tadros@ncbis.co.uk',
                isInCare: false,
                inCareNotes: '',
                isForcesFamily: false,
                fsm: false,
                freeMealReviewDate: '1800-01-01T00:00:00.000+00:00',
                freeMealStartDate: '1800-01-01T00:00:00.000+00:00',
                fsmNotes: '',
                dateOfEntry: '2011-09-07T00:00:00.000+00:00',
                dateOfLeaving: '1800-01-01T00:00:00.000+00:00',
                firstLanguageCode: '000',
                firstLanguage: '',
                isEnglishSecondLanguage: false,
                otherLanguageCode: '000',
                otherLanguage: '',
                boarderStatusCode: '0',
                boarderStatus: ' ',
                countryAddressCode: '001',
                countryAddress: '',
                entryYear: '0',
                enquirySource: '',
                entryYearGroup: '',
                anyRecordLastUpdated: '2025-01-15T13:36:20.007+00:00',
                isPhotoAllowed: true,
                photo: null,
                lastUpdated: '0001-01-01T00:00:00.000+00:00',
                placingAuthorityCode: '',
                placingAuthority: null,
                leavingReasonCode: '011',
                leavingReason: 'University',
                leavingDestinationCode: '',
                leavingDestination: null,
                leavingDestinationPostYear11Code: '',
                leavingDestinationPostYear11: null,
                leavingDestinationPostYear13Code: '',
                leavingDestinationPostYear13: null,
                classTypeCode: '0',
                classType: null,
                isExternal: false,
                forcesFamily: false,
                photoAllowed: true,
                englishSecondLanguage: false,
                inCare: false,
                external: false
            },
            {
                schoolId: 'CL1-NCBIS',
                status: 'Current',
                pupilId: '869',
                admissionNumber: 747,
                pupilCode: 'WASS03',
                familyNumber: '',
                surname: 'Wassef',
                forename: 'Sabine',
                middlename: '',
                displayName: 'Sabine Wassef',
                preferredForename: 'Sabine',
                preferredSurname: 'Wassef',
                genderCode: 'F',
                gender: 'Female',
                dob: '2008-06-08T00:00:00.000+00:00',
                formName: ' ',
                yearGroupCode: '022',
                yearGroup: 'Year 13',
                registrationGroupCode: '0000',
                registrationGroup: ' ',
                registrationGroupText: '',
                houseCode: '0001',
                house: 'Fire',
                ncYearGroupCode: '00',
                ncYearGroup: ' ',
                address: 'Bellagio compound   North investors  opposite gate 1 Al Rehab villa G8',
                postCode: '',
                upn: '',
                studentEmailAddress: 'sabine.wassef@ncbis.co.uk',
                isInCare: false,
                inCareNotes: '',
                isForcesFamily: false,
                fsm: false,
                freeMealReviewDate: '1800-01-01T00:00:00.000+00:00',
                freeMealStartDate: '1800-01-01T00:00:00.000+00:00',
                fsmNotes: '',
                dateOfEntry: '2011-09-07T00:00:00.000+00:00',
                dateOfLeaving: '1800-01-01T00:00:00.000+00:00',
                firstLanguageCode: '000',
                firstLanguage: '',
                isEnglishSecondLanguage: false,
                otherLanguageCode: '000',
                otherLanguage: '',
                boarderStatusCode: '0',
                boarderStatus: ' ',
                countryAddressCode: '001',
                countryAddress: '',
                entryYear: '0',
                enquirySource: '',
                entryYearGroup: '',
                anyRecordLastUpdated: '2025-01-15T13:36:25.130+00:00',
                isPhotoAllowed: true,
                photo: null,
                lastUpdated: '0001-01-01T00:00:00.000+00:00',
                placingAuthorityCode: '',
                placingAuthority: null,
                leavingReasonCode: '',
                leavingReason: null,
                leavingDestinationCode: '',
                leavingDestination: null,
                leavingDestinationPostYear11Code: '',
                leavingDestinationPostYear11: null,
                leavingDestinationPostYear13Code: '',
                leavingDestinationPostYear13: null,
                classTypeCode: '0',
                classType: null,
                isExternal: false,
                forcesFamily: false,
                photoAllowed: true,
                englishSecondLanguage: false,
                inCare: false,
                external: false
            }
        ]);
    }
}
