[
    {
        id: 1001,
        surname: 'Abidi',
        forename: 'Amira',
        yearGroup: '10',
        gender: 'Female',
        attendance: 96.0,
        boarder: false,
        sendStatus: null,
        EAL: false,
        LAC: false,
        ethnicity: 'WBR',
        nationality: 'British',
        dateOfBirth: '2009-05-12'
    },
    {
        id: 1002,
        surname: 'Abidi',
        forename: 'Dylan',
        yearGroup: '7',
        gender: 'Male',
        attendance: 96.2,
        boarder: false,
        sendStatus: null,
        EAL: false,
        LAC: false,
        ethnicity: 'WBR',
        nationality: 'British',
        dateOfBirth: '2012-09-03'
    },
    {
        id: 1003,
        surname: 'Abraham',
        forename: 'Ella',
        yearGroup: '11',
        gender: 'Female',
        attendance: 96.2,
        boarder: '7 Nights',
        sendStatus: null,
        EAL: false,
        LAC: false,
        ethnicity: 'WBR',
        nationality: 'British',
        dateOfBirth: '2008-11-21'
    },
    {
        id: 1004,
        surname: 'Abushi',
        forename: 'Sarah',
        yearGroup: '6',
        gender: 'Female',
        attendance: 96.2,
        boarder: false,
        sendStatus: null,
        EAL: true,
        LAC: false,
        ethnicity: 'OABA',
        nationality: 'Syrian',
        dateOfBirth: '2013-07-15'
    },
    {
        id: 1005,
        surname: 'Adamson',
        forename: 'Ramsey',
        yearGroup: '10',
        gender: 'Male',
        attendance: 90.4,
        boarder: '6 Nights',
        sendStatus: null,
        EAL: false,
        LAC: false,
        ethnicity: 'WBR',
        nationality: 'British',
        dateOfBirth: '2009-02-28'
    },
    {
        id: 1006,
        surname: 'Ainslie',
        forename: 'Benjamin',
        yearGroup: 'Nursery',
        gender: 'Male',
        attendance: 96.8,
        boarder: false,
        sendStatus: null,
        EAL: false,
        LAC: false,
        ethnicity: 'WBR',
        nationality: 'British',
        dateOfBirth: '2020-01-09'
    },
    {
        id: 1007,
        surname: 'Al Fahmy',
        forename: 'Mohammed',
        yearGroup: '7',
        gender: 'Male',
        attendance: 95.2,
        boarder: 'Night',
        sendStatus: null,
        EAL: true,
        LAC: false,
        ethnicity: 'OABI',
        nationality: 'Saudi Arabian',
        dateOfBirth: '2012-08-17'
    },
    {
        id: 1008,
        surname: 'Al Kashab',
        forename: 'Habib',
        yearGroup: '4',
        gender: 'Male',
        attendance: 98.7,
        boarder: false,
        sendStatus: null,
        EAL: true,
        LAC: false,
        ethnicity: 'OABI',
        nationality: 'Qatari',
        dateOfBirth: '2015-04-03'
    },
    {
        id: 1009,
        surname: 'Al Sawi',
        forename: 'Alayna',
        yearGroup: '8',
        gender: 'Female',
        attendance: 95.2,
        boarder: '7 Nights',
        sendStatus: null,
        EAL: true,
        LAC: false,
        ethnicity: 'OABI',
        nationality: 'Emirati',
        dateOfBirth: '2011-12-09'
    },
    {
        id: 1010,
        surname: 'Alexander',
        forename: 'Jemima',
        yearGroup: '9',
        gender: 'Female',
        attendance: 95.8,
        boarder: '6 Nights',
        sendStatus: 'SEND All',
        EAL: false,
        LAC: true,
        ethnicity: 'WBR',
        nationality: 'British',
        dateOfBirth: '2010-06-21'
    }
];
